### ISSUE TITLE
Linking machinery does not work anymore, configuration was unchanged

### ISSUE THREAD

**Issue by hapst3r** [protesilaos/denote#169]
Hej prot,

as always, let me preface with a warm "thank you" for all your great work in the emacs ecosystem. I regularly marvel at the time it must have taken for you to write these absolutely fantastic manuals (which I hope has not mentioned what I am about to talk about :D)

#

I use denote since some time for note taking purposes and am very satisfied. Most important to my workflow are `denote`, `denote-rename-file-using-front-matter`, `denote-link-or-create`, `denote-keywords-add` and `org-insert-link`. I use a silo approach, splitting my notes by subject matters, each subfolder containing a `.dir-locals.el` file.

Today, I updated both emacs (from distro) and emacs packages (from elpaca). After I did that, `denote-link-or-create` would not work anymore (prompting me for a file name for a new file instead of trying to link first), and when I use `org-insert-link` with `denote:` keyword, there is an error saying "No files in denote-directory".

When I visit a file in a silo, the value of `default-directory` is the correct one, pointing to the silo folder. However, the value of `denote-directory` is still the default value `/home/USER/Documents/notes/`, despite my configuration setting the value to something else.

#

Denote configuration (elpaca):
```
(use-package denote
  :demand t
  :custom
  (denote-directory "~/notes/denote/")
  (denote-known-keywords nil)
  (denote-sort-keywords nil)
  (denote-dired-directories (cdr (ffap-all-subdirs denote-directory)))
  :bind
  (("s-n n" . denote)
   ("s-n R" . denote-rename-file-using-front-matter)
   ("s-n r" . denote-rename-file)
   ("s-n c" . denote-link-or-create)
   ("s-n s" . denote-subdirectory)
   ("s-n k" . denote-keywords-add)))
```

Content of .dir-locals.el
`((nil . ((denote-directory . default-directory))))`

#

If you need any other information for debugging purposes, I am happy to provide whatever is needed.

Thanks for you time :)

**Comment by protesilaos** [comment]
> From: hapst3r ***@***.***>
> Date: Wed, 27 Sep 2023 23:49:54 -0700
>
> Hej prot,

Hello there!

> as always, let me preface with a warm "thank you" for all your great
> work in the emacs ecosystem. I regularly marvel at the time it must
> have taken for you to write these absolutely fantastic manuals (which
> I hope has not mentioned what I am about to talk about :D)

You are welcome!

> [... 7 lines elided]

> Today, I updated both emacs (from distro) and emacs packages (from
> elpaca). After I did that, `denote-link-or-create` would not work
> anymore (prompting me for a file name for a new file instead of trying
> to link first), and when I use `org-insert-link` with `denote:`
> keyword, there is an error saying "No files in denote-directory".

> [... 31 lines elided]

> If you need any other information for debugging purposes, I am happy
> to provide whatever is needed.

Elpaca pulls directly from Git, right?  Can you check which commit
Denote is on?  The latest one is dcacd250644d6e2e9108776d18487d0446263f93:
it fixed a regression in 'denote-link-or-create'

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by hapst3r** [comment]
Hej @protesilaos,
after a bit of tinkering, I made 100% sure `denote` is on the commit you mentioned. Unfortunately, this does not seem to fix the issue.

**Comment by protesilaos** [comment]
> From: hapst3r ***@***.***>
> Date: Thu, 28 Sep 2023 22:34:34 -0700
>
> Hej @protesilaos, after a bit of tinkering, I made 100% sure `denote`
> is on the commit you mentioned. Unfortunately, this does not seem to
> fix the issue.

This is strange.  I am trying it now, but it works on my end.  Can you
tell me the steps you follow, so I can try to reproduce the issue?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by MirkoHernandez** [comment]
I recently updated denote and  had the same issue . My silo configuration is the same.

```  emacs-lisp
((nil . ((denote-directory . default-directory)
```
I tried calling  `(denote-directory)`  from a note and it returns the location of the `dir-locals`  directory, not the expected `default-directory`.

The following solution solves the issue  for note creation but could create a problem when linking (I have been using a custom version of  `denote--directory-all-files-recursively`  for links so I don't  have this issue)

``` emacs-lisp
(defun denote--default-directory-is-silo-p ()
  "Return path to silo if `default-directory' is a silo."
  (when-let ((dir-locals (dir-locals-find-file default-directory))
             (found-dir (alist-get 'denote-directory dir-local-variables-alist)))
    (cond
     (found-dir (if (symbolp found-dir)
                    (symbol-value found-dir) found-dir))
     ((listp dir-locals)
      (car dir-locals))
     ((stringp dir-locals)
      dir-locals)
     (t nil))))
```
Apparently the links do not work because of  `denote-file-prompt`. The `when-let ` form stops at the second clause, I'm not sure what modifications are required here. 

``` emacs-lisp
(defun denote-file-prompt (&optional files-matching-regexp)
  "Prompt for file with identifier in variable `denote-directory'.
With optional FILES-MATCHING-REGEXP, filter the candidates per
the given regular expression."
  (when-let ((files (if files-matching-regexp
                    (denote-directory-files-matching-regexp files-matching-regexp)
                  (denote-all-files)))
             (completion-ignore-case read-file-name-completion-ignore-case)
             (file (funcall project-read-file-name-function
                            "Select note: " files nil 'denote--file-history)))
    (add-to-history 'denote--file-history file)
    file))
```
Testing the 2.0.0 version of this function  everything works as expected.

**Comment by protesilaos** [comment]
Thank you @MirkoHernandez!  I just pushed a change for it that should not quit the `when-let` form.

**Comment by hapst3r** [comment]
> From: hapst3r ***@***.***> Date: Thu, 28 Sep 2023 22:34:34 -0700 Hej @protesilaos, after a bit of tinkering, I made 100% sure `denote` is on the commit you mentioned. Unfortunately, this does not seem to fix the issue.
> This is strange. I am trying it now, but it works on my end. Can you tell me the steps you follow, so I can try to reproduce the issue?
> […](#)
> -- Protesilaos Stavrou https://protesilaos.com

Sure, sorry to make you ask for it ^^,

> Thank you @MirkoHernandez! I just pushed a change for it that should not quit the `when-let` form.

Unfortunately, this does not solve the issue for me.

So, what is happening:
1. I open a `dired` that points to my silo
2. I open a note
3. I call `denote-link-or-create` because I want to link to another note in the silo (or create a new note in the silo when it is not already present)
4. I am prompted for file name and keywords. If I provide both, a new note is created using my inputs as parameters.

#

On another note, I am not 100% satisfied with the title but so far failed to come up with another one. If you happen to find one that is more technically fitting, I'm all ears :-)

**Comment by MirkoHernandez** [comment]
Thanks @protesilaos, I tested the fix and it works. I'm  still using the modified  `denote--default-directory-is-silo-p`  though, is this change not required?, currently  it does not seem to set the correct  `denote-directory`.

@hapst3r  I tested using the steps mentioned and it works for me. I'm using the last commit, and  two silos with the same `default-directory`  setup. Calling a denote  inside `dired` creates the mentioned problem, it uses de default `denote-directory` and not the one set in `dir-locals`.

**Comment by hapst3r** [comment]
@protesilaos, as of commit b060dc3, the problem no longer occurs. I don't know why it wouldn't work this morning (I did a `elpaca-update-all` and `denote` _was_ on b060dc3), but it does now.

Cheers!

**Comment by protesilaos** [comment]
> From: Mirko Hernández ***@***.***>
> Date: Sat, 30 Sep 2023 07:27:09 -0700
>
> Thanks @protesilaos, I tested the fix and it works. I'm still using
> the modified `denote--default-directory-is-silo-p` though, is this
> change not required?, currently it does not seem to set the correct
> `denote-directory`.

Can you remind me what the issue was?  I am happy to see it fixed.  The
current version of 'denote--default-directory-is-silo-p':

    (defun denote--default-directory-is-silo-p ()
      "Return path to silo if `default-directory' is a silo."
      (when-let ((dir-locals (dir-locals-find-file default-directory))
                 ((alist-get 'denote-directory dir-local-variables-alist)))
        (cond
         ((listp dir-locals)
          (car dir-locals))
         ((stringp dir-locals)
          dir-locals)
         (t nil))))

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
Thank you @hapst3r!  This is this works, I am closing the issue.

**Comment by MirkoHernandez** [comment]
> Can you remind me what the issue was?  I am happy to see it fixed. 

The  issue occurs when using the `denote` command inside a silo that sets the following:
` ((nil . ((denote-directory . default-directory))))`

Problem 1: Notes are created in the root directory of the silo (.dir-locals location) and not in the current `default-directory`. I'm not sure if this is the expected behavior, maybe it is by design.

Problem 2: Since now the `denote-directory`  is the current default-directory (using the workaround 1indicated below) , `denote-link` only finds possible links inside the current directory and not across the silo, workaround 2 is required.

Problem 3: Unable to follow some links, workaround 2 is required.

Workaround 1
``` emacs-lisp 
(defun denote--default-directory-is-silo-p ()
  "Return path to silo if `default-directory' is a silo."
  (when-let ((dir-locals (dir-locals-find-file default-directory))
             (found-dir (alist-get 'denote-directory dir-local-variables-alist)))
    (cond
     (found-dir (if (symbolp found-dir)
                    (symbol-value found-dir) found-dir))
     ((listp dir-locals)
      (car dir-locals))
     ((stringp dir-locals)
      dir-locals)
     (t nil))))
```
Workaround 2
``` emacs-lisp 
(defun denote--directory-all-files-recursively ()
  "Return list of all files in variable `denote-directory'.
Avoids traversing dotfiles (unconditionally) and whatever matches
`denote-excluded-directories-regexp'."
  (directory-files-recursively
  my-denote-base-directory 
  ;; (denote-directory) 
     directory-files-no-dot-files-regexp
     :include-directories
     (lambda (f)
       (cond
        ((string-match-p "\\`\\." f) nil)
        ((string-match-p "/\\." f) nil)
        ((denote--exclude-directory-regexp-p f) nil)
        ((file-readable-p f))
        (t)))
     :follow-symlinks))
```

Suggested solution: a more flexible `denote-directory` function. 
 - Maybe it could accept more options in the `.dir-locals` file.
 - Maybe design two behaviors for `denote-directory`, return a different directory when creating notes and when linking a note, or following a link .

**Comment by protesilaos** [comment]
> From: Mirko Hernández ***@***.***>
> Date: Sun,  8 Oct 2023 17:33:27 -0700
>
>> Can you remind me what the issue was?  I am happy to see it fixed. 
>
> The  issue occurs when using the `denote` command inside a silo that sets the following:
> ` ((nil . ((denote-directory . default-directory))))`
>
> Problem 1: Notes are created in the root directory of the silo
> (.dir-locals location) and not in the current `default-directory`. I'm
> not sure if this is the expected behavior, maybe it is by design.

Yes, this is the desired behaviour.  The idea is to make the directory
tree a silo.  Meaning that if you want a subdirectory to be its own
silo, you need to add dir-locals at its root.

> [... 43 lines elided]

> Suggested solution: a more flexible `denote-directory` function. 
>  - Maybe it could accept more options in the `.dir-locals` file.

I think I am missing something obvious here.  Are the files in the same
directory or are there subdirectories?  If the latter, then
'default-directory' for the subdirectories will indeed not be able to
find files in the parent directories: the subdir has becomes its own
silo.

Please help me understand this better.  Share sample files and/or
directory structure if needed.

In principle though, I am fine to make things more flexible.

>  - Maybe design two behaviors for `denote-directory`, return a
>  different directory when creating notes and when linking a note, or
>  following a link .

Notwithstanding the above, maybe you can get what you want by 'let'
binding the 'denote-directory' and then calling 'denote'?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by MirkoHernandez** [comment]
> Notwithstanding the above, maybe you can get what you want by 'let'
> binding the 'denote-directory' and then calling 'denote'?

This is the solution that I was using a few months ago, but at some point  the behavior of   `denote-directory` changed and it stopped  working. I just noticed that the option  `denote-user-enforced-denote-directory` works!,  I haven't read the documentation in a while so I was not aware of this, I will try this instead of the  workarounds.

I still think that it is worthwhile to separate the behavior of `denote-directory`  for note creation and for linking. An optional parameter should not break current functionality and would allow users to set the preferred denote workflow in `dir-locals`.  For example, an option for additional directories for links would allow  links to find files outside the silo, and an option for note creation could indicate to always use `default-directory` (no wrapper around denote would be required). An "install denote and configure silo" approach, instead of adding the desired functionality with custom functions. I can provide some of this features if this is in line with denote's design.

> Please help me understand this better.  Share sample files and/or directory structure if needed.

My main usage for denote right now is reference notes.

``` text
- silo-root
  - journal
  - reference
    - alsamixer  -> notes
    - apt - > notes
    - cloc - > notes
    - crontab - > notes
    - doxygen  - > notes
    - etc....
```

So I'm always creating notes in the  `default-directory` , and linking notes across the entire silo.  Adding a `dir-locals` for every subdirectory would be extremely cumbersome ( I think the initial versions of denote worked this way but at some point improvements in how the silos work allowed the `default-directory` option. This is a fantastic feature, I always use it when creating notes.)
