### ISSUE TITLE
In silo, reference to variable "default-directory" doesn't work, jamming all denote-related commands for note creation etc.

### ISSUE THREAD

**Issue by hapst3r** [protesilaos/denote#218]
Hello @protesilaos 

after a recent update to denote (like ~2 weeks ago or so), whenever I issue a `denote`-related command in a silo -- such as `denote-keywords-add`, `denote-link-or-create` or `denote` --, the command is not executed, with this error message in the `*Messages*` buffer: denote--directory-all-files-recursively: Wrong type argument: stringp, default-directory.

Before this update -- currently I am on version 2.2.4, commit dfb517a8 --, those commands would work just fine, creating new notes in said silo, adding keywords to current note, etc.

This is the relevant part of my `denote` config:
```
(use-package denote
  :demand t
  :custom
  (denote-directory "~/notes/denote/")
  (denote-known-keywords nil)
  (denote-sort-keywords nil)
  (denote-dired-directories (cdr (ffap-all-subdirs denote-directory))))
```

The directory structure is ~/notes/denote/SILOS, each $SILO containing a `.dir-locals.el` with the content suggested in the manual: `((nil . ((denote-directory . default-directory))))`.

Executing `helpful-variable` on `denote-directory` from within a $SILO directory, the value is `default-directory`, with the original value `/home/USER/Documents/notes`. The value of `default-directory` correctly points to the $SILO in which I reside issuing the command.

If I can provide further information, please tell me which (and how to obtain them).

Have a good day :)

**Comment by jeanphilippegg** [comment]
Hello hapst3r,

Sorry about this issue. This feature has been broken by my pull request
(#211). I had overlooked this way of setting `denote-directory` (in
`.dir-locals.el`).

I have reverted my changes in a new pull request.

**Comment by hapst3r** [comment]
Hej @jeanphilippegg 

thanks for the quick response and fix. I hope this gets merged soon so I can use denote the way I usually do. Yet, it is good to know that it is not related to something strange that is hard to fix or a problem on my part.

**Comment by jeanphilippegg** [comment]
No worry!

Until this is merged, you can use
```
((nil . ((denote-directory . "/path/to/your/silo/"))))
```
in your `.dir-locals.el` and accept the warning that the value may not be safe.

**Comment by protesilaos** [comment]
Hello @hapst3r! I just merged it. Please check if everything is okay there.

**Comment by hapst3r** [comment]
> Hello @hapst3r! I just merged it. Please check if everything is okay there.

Hej @protesilaos! I just checked, and unfortunately it does not resolve the issue mentioned before. In the meantime, I will use the fix proposed by @jeanphilippegg.

One of these days, I will try `emacs -Q` to see if this has to do with my setup (I would wonder though since I haven't changed anything related in quite a while).

**Comment by protesilaos** [comment]
I think we can safely close this. If the issue resurfaces, please report it. Thank you!
